name = "estate-wealth-my"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
pages_build_output_dir = ".next"

[[routes]]
handle = "filesystem"

[[routes]]
handle = "resource"
pattern = "/_next/static/*"

[[routes]]
handle = "resource"
pattern = "/public/*"

[[routes]]
handle = "missing"
pattern = "/.*\\.(json|xml|txt|js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)"
status = 404

[[routes]]
handle = "rewrite"
pattern = "/*"
status = 200
