'use client';

import { useState, useRef } from 'react';
import { Download, Printer, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface PDFDownloadButtonProps {
  contentRef: React.RefObject<HTMLDivElement>;
  filename?: string;
  title?: string;
}

export default function PDFDownloadButton({
  contentRef,
  filename = 'estate-planning-results',
  title = 'Your Estate Planning Results'
}: PDFDownloadButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownloadPDF = async () => {
    if (!contentRef.current) return;

    setIsGenerating(true);

    try {
      // Temporarily show all content and hide buttons for capture
      const buttons = contentRef.current.querySelectorAll('.no-print');
      buttons.forEach(btn => (btn as HTMLElement).style.display = 'none');

      // Capture the content as canvas
      const canvas = await html2canvas(contentRef.current, {
        scale: 2, // Higher quality
        useCORS: true,
        logging: false,
        backgroundColor: '#fdf8f3', // brand-cream
        windowWidth: 1200,
      });

      // Restore buttons
      buttons.forEach(btn => (btn as HTMLElement).style.display = '');

      // Calculate PDF dimensions (A4)
      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      // Create PDF
      const pdf = new jsPDF('p', 'mm', 'a4');
      let heightLeft = imgHeight;
      let position = 0;

      // Add first page
      pdf.addImage(
        canvas.toDataURL('image/png'),
        'PNG',
        0,
        position,
        imgWidth,
        imgHeight
      );
      heightLeft -= pageHeight;

      // Add additional pages if content is longer than one page
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(
          canvas.toDataURL('image/png'),
          'PNG',
          0,
          position,
          imgWidth,
          imgHeight
        );
        heightLeft -= pageHeight;
      }

      // Add footer to last page
      const pageCount = pdf.getNumberOfPages();
      pdf.setPage(pageCount);
      pdf.setFontSize(8);
      pdf.setTextColor(128);
      pdf.text(
        `Generated by Estate Wealth My | ${new Date().toLocaleDateString('en-MY')}`,
        105,
        290,
        { align: 'center' }
      );

      // Download
      const timestamp = new Date().toISOString().split('T')[0];
      pdf.save(`${filename}_${timestamp}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try using the Print option instead.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-col sm:flex-row gap-3 justify-center no-print">
      <button
        onClick={handleDownloadPDF}
        disabled={isGenerating}
        className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-brand-gold text-white font-medium rounded-lg hover:bg-brand-goldHover transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-5 h-5 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <Download className="w-5 h-5" />
            Download PDF
          </>
        )}
      </button>

      <button
        onClick={handlePrint}
        className="inline-flex items-center justify-center gap-2 px-6 py-3 border-2 border-brand-gold text-brand-gold font-medium rounded-lg hover:bg-brand-gold/10 transition-colors"
      >
        <Printer className="w-5 h-5" />
        Print Results
      </button>
    </div>
  );
}
